### ISSUE TITLE
yarn dev raise an error

### ISSUE THREAD

**Issue by dstoever** [AhmedElywa/oah-admin#34]
The call "yarn dev" raise the following error:

 ERROR 

There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html  Couldn't find layout component at "/mnt/Data Linux/Projekte/checkmallorca.admin.oha/src/layouts/index.

  13 | } catch (e) {
  14 |   if (e.toString().indexOf("Error: Cannot find module") !== -1) {
> 15 |     throw new Error("Couldn't find layout component at \"" + GATSBY_LAYOUT_COMPONENT_PATH + ".\n\n" + "Please create layout component in that location or specify path to layout component in gatsby-config.js");
     |           ^
  16 |   } else {
  17 |     // Logging the error for debugging older browsers as there is no way
  18 |     // to wrap the thrown error in a try/catch.

  WebpackError: Couldn't find layout component at "/mnt/Data Linux/Projekte/checkmallorca.admin.oha/src/layouts/index.
  
  - wrap-page.js:15 Object../node_modules/gatsby-plugin-layout/wrap-page.js
    node_modules/gatsby-plugin-layout/wrap-page.js:15:11
  
  - gatsby-ssr.js:3 Object../node_modules/gatsby-plugin-layout/gatsby-ssr.js
    node_modules/gatsby-plugin-layout/gatsby-ssr.js:3:27
  

—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
35 pages                                                                                                                         FAILED                                                                                                                         oah-admin
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by AhmedElywa** [comment]
The problem you see is from `gatsby-plugin-layout` plugin it's need layout component in this path `src/layouts/index` and it's already there. can you copy your `gatsby-config.js` file content here please ?
